/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ticketEventDialog.java
 *
 * Created on 29-10-2009, 12:58:11
 */

package GUI;
import java.text.ParseException;

import dal.Event;
import dal.Customer;
import dalinterface.DALException;
import dao.EventDAO;

/**
 *
 * @author Michael
 */
public class ticketEventDialog extends javax.swing.JDialog {

    /** Creates new form ticketEventDialog */
    public ticketEventDialog(java.awt.Frame parent, boolean modal, Event event, Customer customer) {
        super(parent, modal);
        initComponents();
        TitelJLabel.setText(event.getTitel());
        DateSTARTJLabel.setText(event.getDateStartString());
        DateFINISHJLabel.setText(event.getDateFinishString());
        StageJLabel.setText(event.getStage());
        PrisOriInputJLabel1.setText(Double.toString(event.getPrice()));
        ArtistJLabel.setText(event.getArtist());

        try {
			BilletInputJLabel.setText(
			        event.getArtist().substring(0, 2)+
			        event.getEventID()+
			        new EventDAO().getTicketSold(event.getEventID())+1
			        );
		} catch (DALException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		} catch (ParseException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
        if (customer.getDiscount().equalsIgnoreCase("SHOW") ) {
            RabatInputJLabel.setText(event.getShowDiscount()+"%");
            double pris = event.getPrice()-((event.getPrice()/100)*event.getShowDiscount());
            PrisInputJLabel.setText(pris+"kr");
        }else{
            if (customer.getDiscount().equalsIgnoreCase("NORMAL") ) {
                RabatInputJLabel.setText(+event.getPortalisDiscount()+"%");
                double pris = event.getPrice()-((event.getPrice()/100)*event.getPortalisDiscount());
                PrisInputJLabel.setText(pris+"kr");
            }else{
                RabatInputJLabel.setText(0+"%");

                PrisInputJLabel.setText(event.getPrice()+"kr");
            }
        }


    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        PortalenTextJLabel = new javax.swing.JLabel();
        TitelJLabel = new javax.swing.JLabel();
        TextJLabel1 = new javax.swing.JLabel();
        DateSTARTJLabel = new javax.swing.JLabel();
        DateFINISHJLabel = new javax.swing.JLabel();
        BindeJLabel = new javax.swing.JLabel();
        TextJLabel2 = new javax.swing.JLabel();
        StageJLabel = new javax.swing.JLabel();
        KundeJLabel = new javax.swing.JLabel();
        KundeInputJLabel = new javax.swing.JLabel();
        RabetJLabel = new javax.swing.JLabel();
        PrisJLabel = new javax.swing.JLabel();
        RabatInputJLabel = new javax.swing.JLabel();
        PrisInputJLabel = new javax.swing.JLabel();
        BilletInputJLabel = new javax.swing.JLabel();
        BilletJLabel = new javax.swing.JLabel();
        ArtistJLabel = new javax.swing.JLabel();
        PrisOriJLabel = new javax.swing.JLabel();
        PrisOriInputJLabel1 = new javax.swing.JLabel();
        TextJLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        PortalenTextJLabel.setFont(new java.awt.Font("Bodoni MT", 0, 18)); // NOI18N
        PortalenTextJLabel.setText("Portalen Præsenterer:");

        TitelJLabel.setFont(new java.awt.Font("Bodoni MT Black", 1, 24)); // NOI18N
        TitelJLabel.setText("Airbourne");

        TextJLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        TextJLabel1.setText("Den");

        DateSTARTJLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        DateSTARTJLabel.setText("1000-01-01 00:00:00");

        DateFINISHJLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        DateFINISHJLabel.setText("1000-01-01 00:00:00");

        BindeJLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        BindeJLabel.setText("-");

        TextJLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        TextJLabel2.setText("I");

        StageJLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        StageJLabel.setText("Store Scene");

        KundeJLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        KundeJLabel.setText("Kunde:");

        KundeInputJLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        KundeInputJLabel.setText("Michael Juhl");

        RabetJLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        RabetJLabel.setText("Rabat:");

        PrisJLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        PrisJLabel.setText("Din Pris:");

        RabatInputJLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        RabatInputJLabel.setText("25%");

        PrisInputJLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        PrisInputJLabel.setText("200kr");

        BilletInputJLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        BilletInputJLabel.setText("D291F8IR");

        BilletJLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        BilletJLabel.setText("BilletID:");

        ArtistJLabel.setFont(new java.awt.Font("Bodoni MT", 1, 12)); // NOI18N
        ArtistJLabel.setText("Airbourne");

        PrisOriJLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        PrisOriJLabel.setText("Pris:");

        PrisOriInputJLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        PrisOriInputJLabel1.setText("200kr");

        TextJLabel3.setFont(new java.awt.Font("Bodoni MT", 1, 12)); // NOI18N
        TextJLabel3.setText("Med");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(PortalenTextJLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 672, Short.MAX_VALUE)
                                .addComponent(BilletJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BilletInputJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(KundeJLabel)
                                        .addGap(18, 18, 18)
                                        .addComponent(KundeInputJLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 640, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(RabetJLabel)
                                        .addGap(18, 18, 18)
                                        .addComponent(RabatInputJLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 643, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(PrisOriJLabel)
                                        .addGap(33, 33, 33)
                                        .addComponent(PrisOriInputJLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 317, Short.MAX_VALUE)
                                        .addGap(326, 326, 326))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(PrisJLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(PrisInputJLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 642, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(TextJLabel1)
                                            .addComponent(TextJLabel2))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(DateSTARTJLabel)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(BindeJLabel)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(DateFINISHJLabel))
                                            .addComponent(StageJLabel))))
                                .addGap(280, 280, 280))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(TextJLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(ArtistJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(TitelJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(BilletInputJLabel)
                        .addComponent(BilletJLabel))
                    .addComponent(PortalenTextJLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TitelJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextJLabel3)
                    .addComponent(ArtistJLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextJLabel1)
                    .addComponent(DateSTARTJLabel)
                    .addComponent(BindeJLabel)
                    .addComponent(DateFINISHJLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextJLabel2)
                    .addComponent(StageJLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(KundeJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(KundeInputJLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RabetJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RabatInputJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PrisOriJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PrisOriInputJLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PrisJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PrisInputJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>

    /**
    * @param args the command line arguments
    
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ticketEventDialog dialog = new ticketEventDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }*/

    // Variables declaration - do not modify
    private javax.swing.JLabel ArtistJLabel;
    private javax.swing.JLabel BilletInputJLabel;
    private javax.swing.JLabel BilletJLabel;
    private javax.swing.JLabel BindeJLabel;
    private javax.swing.JLabel DateFINISHJLabel;
    private javax.swing.JLabel DateSTARTJLabel;
    private javax.swing.JLabel KundeInputJLabel;
    private javax.swing.JLabel KundeJLabel;
    private javax.swing.JLabel PortalenTextJLabel;
    private javax.swing.JLabel PrisInputJLabel;
    private javax.swing.JLabel PrisJLabel;
    private javax.swing.JLabel PrisOriInputJLabel1;
    private javax.swing.JLabel PrisOriJLabel;
    private javax.swing.JLabel RabatInputJLabel;
    private javax.swing.JLabel RabetJLabel;
    private javax.swing.JLabel StageJLabel;
    private javax.swing.JLabel TextJLabel1;
    private javax.swing.JLabel TextJLabel2;
    private javax.swing.JLabel TextJLabel3;
    private javax.swing.JLabel TitelJLabel;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration

}
