/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * DialogNewUser.java
 *
 * Created on 05-11-2009, 09:00:03
 */


package GUI;

import java.awt.event.ActionEvent;
import dal.User;
import dao.UserDAO;
import daoInterface.DALException;

/**
 *
 * @author Casper
 */
public class UserEditDialog extends javax.swing.JDialog {

	private User user;
	private UserList userTable;
    public UserEditDialog(java.awt.Frame parent, UserList userTable, boolean modal, User user) {
        super(parent, modal);
        this.userTable = userTable;
        this.user = user;
        initComponents();
        setTitle("Rediger bruger: " + user.getUserID());
        setLocationRelativeTo(null);
        setVisible(true);
        
        
       
        
      //input for edit
		nameInputField.setText(user.getName());
		cprInputField.setText(new Integer(user.getCPR()).toString());
		phoneInputField.setText(new Integer(user.getPhone()).toString());
		
		addressInputField.setText(user.getAdresse());
		passwordInputField.setText(user.getPassword());
		
		//
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        nameInputField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        cprInputField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        phoneInputField = new javax.swing.JTextField();
        sexComboBox = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        rankComboBox = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        addressInputField = new javax.swing.JTextField();
        errorLabel = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        saveUserButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        passwordInputField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        rankComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Billetsælger", "Kontormedarbejder", "Admin", "Deaktiveret" }));
        
        errorLabel.setText("");
        
        jLabel1.setText("Navn:");

        jLabel2.setText("CPR:");

        jLabel3.setText("TLF:");

        sexComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Mand", "Kvinde" }));
        
        jLabel4.setText("Køn:");

        jLabel5.setText("Password:");

        jLabel6.setText("Rank");
        
        jLabel7.setText("Adresse");
        
        jLabel8.setText("");

        jLabel9.setText(" ");

        jLabel10.setText(" ");

        jLabel11.setText(" ");

        jLabel12.setText(" ");

        jLabel13.setText(" ");

        saveUserButton.setText("Gem");
        saveUserButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveUserButtonActionPerformed(evt);
            }
        });

        cancelButton.setText("Luk");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
            	cancelButtonActionPerformed(evt);
            }
        });
        //Load information into fields
        nameInputField.setText(user.getName());
        cprInputField.setText(new Integer(user.getCPR()).toString());
        phoneInputField.setText(new Integer(user.getPhone()).toString());
        addressInputField.setText(user.getAdresse());
        passwordInputField.setText(user.getPassword());
        sexComboBox.setSelectedItem(user.getGender());
        rankComboBox.setSelectedItem(user.getRank());
        
        
        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(saveUserButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cancelButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(passwordInputField, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(sexComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(phoneInputField, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                            .addComponent(cprInputField, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                            .addComponent(nameInputField, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                            .addComponent(jLabel7)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(rankComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(errorLabel)
                            .addComponent(addressInputField, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE))
                        .addGap(6, 6, 6)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 243, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 243, Short.MAX_VALUE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 243, Short.MAX_VALUE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 243, Short.MAX_VALUE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, 243, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameInputField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cprInputField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(phoneInputField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sexComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addressInputField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(passwordInputField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rankComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(errorLabel)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveUserButton)
                    .addComponent(cancelButton))
                .addContainerGap(67, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>

    protected void cancelButtonActionPerformed(ActionEvent evt) {
    	this.dispose();
	}

	private void saveUserButtonActionPerformed(java.awt.event.ActionEvent evt) {
		//check inputs
        //navn
        if (nameInputField.getText().equals("")) {
			errorLabel.setText("<html><FONT COLOR=RED>Fejl: Navn kan ikke vaere tom</FONT></html>");
			return;
		}
        //cpr
        if (cprInputField.getText().equals("")) {
        	errorLabel.setText("<html><FONT COLOR=RED>Fejl: CPR # kan ikke vaere tom</FONT></html>");
			return;
		}

       //tlf
        if (phoneInputField.getText().equals("")) {
        	errorLabel.setText("<html><FONT COLOR=RED>Fejl: telefon # kan ikke vaere tom</FONT></html>");
			return;
		}
        if (phoneInputField.getText().length() > 8) {
        	errorLabel.setText("<html><FONT COLOR=RED>Fejl: telefon nr. er for stort</FONT></html>");
			return;
		}
        try {
			new Integer(phoneInputField.getText());
		} catch (NumberFormatException e1) {
			errorLabel.setText("<html><FONT COLOR=RED>Fejl: telefon nr. ugyldigt, brug kun tal</FONT></html>");
			return;
		}

        //adresse
        if (addressInputField.getText().equals("")) {
        	errorLabel.setText("<html><FONT COLOR=RED>Fejl: Adresse kan ikke vaere tom</FONT></html>");
			return;
		}
        //password
        if (passwordInputField.getText().equals("")) {
        	errorLabel.setText("<html><FONT COLOR=RED>Fejl: password kan ikke vaere tom</FONT></html>");
			return;
		}
       
        saveUserButton.setEnabled(false);
        
		UserDAO userDAO = new UserDAO();
		try {
			user.setName(nameInputField.getText());
			user.setCPR(Integer.valueOf(cprInputField.getText()));
			user.setPhone(Integer.valueOf(phoneInputField.getText()));
			user.setGender((String)sexComboBox.getSelectedItem());
			user.setAdresse(addressInputField.getText());
			user.setPassword(passwordInputField.getText());
			user.setRank((String)rankComboBox.getSelectedItem());
			
			userDAO.updateUser(user.getUserID(), user);
			
			/*
			userDAO.createUser(new User(
					nameInputField.getText()
					, Integer.valueOf(cprInputField.getText())
					, (String)sexComboBox.getSelectedItem()
					, Integer.valueOf(phoneInputField.getText())
					, addressInputField.getText()
					, passwordInputField.getText()
					, (String)rankComboBox.getSelectedItem()
					));
			*/
			
		} catch(NumberFormatException e) {
			e.printStackTrace();
			errorLabel.setText("<html><FONT COLOR=RED>Fejl i input!</FONT></html>");
		} catch (DALException e) {
			errorLabel.setText("<html><FONT COLOR=RED>Fejl: Kan ikke forbinde til database, proev igen</FONT></html>");
			e.printStackTrace();
		}
		userTable.updateTable();
		this.dispose();
    }

    private void passwordInputFieldActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    /**
    * @param args the command line arguments
    */
    /*
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DialogNewUser dialog = new DialogNewUser(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    */

    // Variables declaration - do not modify
    private javax.swing.JButton saveUserButton;
    private javax.swing.JButton cancelButton;
    private javax.swing.JComboBox sexComboBox;
    private javax.swing.JComboBox rankComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField nameInputField;
    private javax.swing.JTextField cprInputField;
    private javax.swing.JTextField phoneInputField;
    private javax.swing.JTextField addressInputField;
    private javax.swing.JTextField passwordInputField;
    private javax.swing.JLabel errorLabel;
    // End of variables declaration

}
